backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "src/settings/global.md"
        label: "Global Settings"
        name: "global-params"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "global-settings"}
          - {label: Site Title, name: siteTitle, widget: string}
          - {label: Site Url, name: siteUrl, widget: string, required: false}
          - {label: Site Description, name: siteDescription, widget: text, required: false}
          - {label: Logo, name: logo, widget: image, required: true}
          - {label: Logo Title, name: logoTitle, widget: string}
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - {label: Twitter Site Account, name: twitterSiteAccount, widget: string, required: false}
              - {label: Twitter Creator Account, name: twitterCreatorAccount, widget: string, required: false}
              - {label: Header Meta / Scripts, name: headerScripts, widget: text, required: false}

  - name: "links"
    label: "Links"
    create: true
    editor:
    preview: false
    files:
    - file: "src/settings/links.md"
      label: "Links"
      name: "navlinks"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "nav-links"}
        - label: "Header Links"
          name: "headerlinks"
          widget: "list"  
          fields:
            - label: Items
              name: item
              widget: object
              fields:
                - {label: "Title", name: title, widget: string}
                - {label: "URL", name: url, widget: string, default: "/"}
                - {label: "Open in new window?", name: newwindow, widget: "boolean", default: "false"}
                - {label: "Glyph Icon", name: icon, widget: "string"}
        - label: "Footer Links"
          name: "footerlinks"
          widget: "list"
          fields:
            - label: Items
              name: item
              widget: object
              fields:
                - {label: "Title", name: title, widget: string}
                - {label: "URL", name: url, widget: string, default: "/"}
                - {label: "Open in new window?", name: newwindow, widget: "boolean", default: "false"}
                - {label: "Glyph Icon", name: icon, widget: "string"}

  - name: "casestudy"
    label: "Case Study"
    folder: "src/pages/case-studies"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "case-study"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: Image, name: image, widget: image}
      - {label: "Date", name: date, widget: datetime, default: "Date"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Display in homepage?", name: "homepage", widget: "boolean", default: false}
      - label: "Customer"
        name: "customer"
        widget: object
        fields:
          - {label: "Name", name: name, widget: string, default: "Emmet"}
          - {label: "Profile", name: profile, widget: text, default: "Customer Profile"}
          - {label: "Web", name: web, widget: string, default: "url"}
      - label: "Case Study"
        name: "casestudy"
        widget: object
        fields:
          - {label: "Description", name: description, widget: markdown, default: "Description"}
          - {label: "Focus", name: focus, widget: markdown, default: "Focus"}
          - {label: "Challenges", name: challenges, widget: markdown, default: "challenges"}
          - {label: "Solution", name: solution, widget: markdown, default: "solution"}
          - {label: "Benefits", name: benefits, widget: markdown, default: "benefits"}
          - {label: "Technology", name: technology, widget: markdown, default: "technology"}

  - name: "offerings"
    label: "Offering"
    folder: "src/pages/offerings"
    create: true
    editor:
      preview: false
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "offering"}
      - {label: Image, name: image, widget: image}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Order (Priotity)", name: "order", widget: "number", default: 1, required: true}
      - {label: "Align Content", name: "align", widget: "select", options: ["left", "right"], required: true}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/team/team.md"
        label: "Teams"
        name: "teams"
        editor:
          preview: false
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "teams-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/teams"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Team title", name: "teamTitle", widget: "text"}
          - {label: "Team Description", name: "teamDescription", widget: "text"}
          - label: "Team"
            name: "team"
            widget: "list"
            fields:
              - label: Person
                name: person
                widget: object
                fields:
                  - {label: Name, name: name, widget: string, default: "Emmet"}
                  - {label: Title, name: title, widget: string, default: "Solution Architect"}
                  - {label: Avatar, name: avatar, widget: image, default: "/img/emmet.jpg"}
                  - {label: Quote, name: quote, widget: "text", default: "About me"}
                  - {label: Background, name: background, widget: string, default: "darkgray"}
                  - {label: "Facebook Site url", name: "fbsiteurl", widget: string, required: false}
                  - {label: "Twitter Site url", name: "twtrsiteurl", widget: string, required: false}
                  - {label: "Linkedin Site url", name: "lnkdnsiteurl", widget: string, required: false}
                  - {label: "Github Site url", name: "githubsiteurl", widget: string, required: false}
